server:
  port: 8088
spring:
  data:
    mongodb:
      host: 139.9.157.50
      port: 27017
      database: chats
      username: "group11"
      password: "123456"

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB